name: SAST Scan
on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/main.yml

jobs:
  semgrep-SAST:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci --json --output=semgrep-results.json

      - name: Save Results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-ci-results
          path: semgrep-results.json
          retention-days: 7

  trigger-docker-workflow:
    needs: build
    uses: ./.github/workflows/build.yml  # Calls the Docker build workflow