name: CI/CD

on: [push]

jobs:
  sast_scan:
    name: Run Semgrep SAST scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v5.5.0
      with:
        python-version: 3.8

    - name: Install Semgrep  
      run: pip install semgrep

    - name: Run Semgrep 
      run: semgrep scan --config=auto --json --output=semgrep-results.json

    - name: Save Results
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-results
        path: semgrep-results.json
        retention-days: 7
